# Generated by Django 3.0.5 on 2020-05-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0002_auto_20200524_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='nombre_alimento',
            field=models.CharField(blank=True, max_length=30, verbose_name='nombres'),
        ),
    ]
