# Generated by Django 3.0.5 on 2020-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentacion", "0003_auto_20200524_0031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentacion",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
        ),
    ]
