# Generated by Django 3.0.5 on 2020-05-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20200526_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="nombres"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="apellidos"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="nombres"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="apellidos"
            ),
        ),
    ]
