from .views import (
    CreateHistoriaView,
    HistoriaListView,
    UpdateHistoriaView,
    DeleteHistoriaView,
    SendReceipt,
    HistoriaPDFReportView,
    EnfermedadListView,
    CreateEnfermedadView,
    UpdateEnfermedadView,
    DeleteEnfermedadView,
)
from django.conf.urls import url

urlpatterns = [
    url(
        r"^(?P<uuid>[-\w]+)/historias/lista-historias/$",
        HistoriaListView.as_view(),
        name="lista-historias",
    ),
    url(
        r"^(?P<uuid>[-\w]+)/historias/crear-historias/$",
        CreateHistoriaView.as_view(),
        name="crear-historias",
    ),
    url(
        r"^historias/(?P<uuid>[-\w]+)/(?P<uuid2>[-\w]+)/editar-historias/$",
        UpdateHistoriaView.as_view(),
        name="editar-historias",
    ),
    url(
        r"^historias/(?P<uuid>[-\w]+)/eliminar-historias/$",
        DeleteHistoriaView.as_view(),
        name="eliminar-historias",
    ),
    url(
        r"^historias/(?P<uuid>[-\w]+)/enviar/$",
        SendReceipt.as_view(),
        name="enviar-historia",
    ),
    url(
        r"^historias/(?P<uuid>[-\w]+)/reporte/$",
        HistoriaPDFReportView.as_view(),
        name="report-pdf",
    ),
    url(
        r"enfermedad/lista-enfermedad/$",
        EnfermedadListView.as_view(),
        name="lista-enfermedad",
    ),
    url(
        r"enfermedad/crear-enfermedad/$",
        CreateEnfermedadView.as_view(),
        name="crear-enfermedad",
    ),
    url(
        r"enfermedad/(?P<uuid>[-\w]+)/editar-enfermedad/$",
        UpdateEnfermedadView.as_view(),
        name="editar-enfermedad",
    ),
    url(
        r"enfermedad/(?P<uuid>[-\w]+)/eliminar-enfermedad/$",
        DeleteEnfermedadView.as_view(),
        name="eliminar-enfermedad",
    ),
]
