# Generated by Django 3.0.5 on 2020-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicacion",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
        ),
    ]
