# Generated by Django 3.0.5 on 2020-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiaclinica",
            name="hora_mayor_apetito",
            field=models.CharField(
                choices=[
                    ("0h", "00"),
                    ("1h", "1AM"),
                    ("2h", "2AM"),
                    ("3h", "3AM"),
                    ("4h", "4AM"),
                    ("5h", "5AM"),
                    ("6h", "6AM"),
                    ("7h", "7AM"),
                    ("8h", "8AM"),
                    ("9h", "9AM"),
                    ("10h", "10AM"),
                    ("11h", "11AM"),
                    ("12h", "12PM"),
                    ("13h", "1PM"),
                    ("14h", "2PM"),
                    ("15h", "3PM"),
                    ("16h", "4PM"),
                    ("17h", "5PM"),
                    ("18h", "6PM"),
                    ("19h", "7PM"),
                    ("20h", "8PM"),
                    ("21h", "9PM"),
                    ("22h", "10PM"),
                    ("23h", "11PM"),
                ],
                default="0h",
                max_length=4,
            ),
        ),
    ]
