# Generated by Django 3.0.5 on 2020-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_auto_20200523_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
    ]
