# Generated by Django 3.0.5 on 2020-05-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alimentacion", "0006_auto_20200527_1943"),
        ("historias", "0005_lineaalegia"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineaAlergia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("efectos_secundarios", models.CharField(max_length=200)),
                (
                    "causa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alimentacion.Alimentacion",
                    ),
                ),
                (
                    "hisotoria_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias.HistoriaClinica",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="LineaAlegia",),
    ]
