# Generated by Django 3.0.5 on 2020-05-28 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alimentacion", "0006_auto_20200527_1943"),
        ("historias", "0006_auto_20200527_2324"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineaConsumo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frecuencia_ejercicio",
                    models.CharField(
                        choices=[
                            ("0", "Muy baja"),
                            ("1", "Baja"),
                            ("2", "Media"),
                            ("3", "Alta"),
                            ("4", "Muy alta"),
                        ],
                        default="0D",
                        max_length=2,
                    ),
                ),
                (
                    "alimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alimentacion.Alimentacion",
                    ),
                ),
                (
                    "hisotoria_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias.HistoriaClinica",
                    ),
                ),
            ],
        ),
    ]
