# Generated by Django 3.0.5 on 2020-05-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historias", "0007_lineaconsumo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineaconsumo",
            old_name="frecuencia_ejercicio",
            new_name="frecuencia",
        ),
    ]
