# Generated by Django 3.0.5 on 2020-05-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alimentacion", "0006_auto_20200527_1943"),
        ("historias", "0008_auto_20200528_0139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineaconsumo",
            name="frecuencia",
            field=models.CharField(
                choices=[
                    ("0", "Muy baja"),
                    ("1", "Baja"),
                    ("2", "Media"),
                    ("3", "Alta"),
                    ("4", "Muy alta"),
                ],
                default="0",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="LineaReceta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posologia", models.FloatField(blank=True, default=1.0, null=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("2", "Cada 2 horas"),
                            ("3", "Cada 3 horas"),
                            ("4", "Cada 4 horas"),
                            ("5", "Cada 5 horas"),
                            ("6", "Cada 6 horas"),
                            ("12", "Cada 12 horas"),
                        ],
                        default="2",
                        max_length=2,
                    ),
                ),
                (
                    "hisotoria_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias.HistoriaClinica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineaMedicamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posologia", models.FloatField(blank=True, default=1.0, null=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("2", "Cada 2 horas"),
                            ("3", "Cada 3 horas"),
                            ("4", "Cada 4 horas"),
                            ("5", "Cada 5 horas"),
                            ("6", "Cada 6 horas"),
                            ("12", "Cada 12 horas"),
                        ],
                        default="2",
                        max_length=2,
                    ),
                ),
                (
                    "hisotoria_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias.HistoriaClinica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineaDieta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField(blank=True, default=1.0, null=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("2", "Cada 2 horas"),
                            ("3", "Cada 3 horas"),
                            ("4", "Cada 4 horas"),
                            ("5", "Cada 5 horas"),
                            ("6", "Cada 6 horas"),
                            ("12", "Cada 12 horas"),
                        ],
                        default="2",
                        max_length=2,
                    ),
                ),
                (
                    "alimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alimentacion.Alimentacion",
                    ),
                ),
                (
                    "hisotoria_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias.HistoriaClinica",
                    ),
                ),
            ],
        ),
    ]
