# Generated by Django 3.0.5 on 2020-05-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medicacion", "0002_auto_20200526_1726"),
        ("historias", "0009_auto_20200528_0245"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineamedicamento",
            name="alimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicacion.Medicacion",
            ),
        ),
        migrations.AddField(
            model_name="lineareceta",
            name="alimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicacion.Medicacion",
            ),
        ),
    ]
