# Generated by Django 3.0.5 on 2020-05-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historias", "0010_auto_20200528_0247"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineamedicamento", old_name="alimento", new_name="medicamento",
        ),
        migrations.RenameField(
            model_name="lineareceta", old_name="alimento", new_name="medicamento",
        ),
    ]
