# Generated by Django 3.0.5 on 2020-05-29 02:29

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0013_enfermedad_lineaenfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaenfermedad',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
