# Generated by Django 3.0.5 on 2020-05-29 02:34

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0014_lineaenfermedad_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaenfermedad',
            name='uuid',
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
